### ISSUE TITLE
Inception

### ISSUE THREAD

**Issue by vorburger** [enola-dev/enola#171]
I will implement [Inception](https://en.wikipedia.org/wiki/Inception), and make loaded _Entity Kinds_ appear as _Entities_ themselves.

These entities will have the "schema" as a #75 `data`.

**Comment by gabrielh** [comment]
+1

**Comment by vorburger** [comment]
WIP https://github.com/enola-dev/enola/compare/main...vorburger:enola:inception

will work further on this some later time
