### ISSUE TITLE
Tag validation

### ISSUE THREAD

**Issue by gabrielh** [enola-dev/enola#216]
As tags are freeform, one possible problem is the risk of collisions or double use of tags. There multiple options here (1) replace tags with fields, (2) type the value (3) add an "external" validator. 
For option 3 we could add a protobuf file that contains the list of the tag keys, document their purpose and specifies the type of the argument.

**Comment by vorburger** [comment]
@gabrielh Enola is in the process of fundamentally changing; those "tags" will disappear together with the `Entity` proto which I'll be deleting some time in the comings weeks, or so. The new architecture is based on Linked Data standards, where everything is an IRI, and the equivalent of what used to be tags will be properties, which are themselves IRI - which makes the model extensible without any risk of collisions or double use of tags.

As for external validation, see also #230.

I'm therefore closing this issue now; hope you don't mind.
