### ISSUE TITLE
Support external validation of a data model

### ISSUE THREAD

**Issue by gabrielh** [enola-dev/enola#230]
Tags allow custom labeling of various things in Enola. I see them as an open format, namely an extensibility feature, that will can be specific to particular data model and internal or external tooling that leverages Enola. 
Thus I propose that Enola supports the external validation of data models.

**Comment by vorburger** [comment]
@gabrielh as just posted on #216, Enola is considerably changing.

The external validation of data models would be based on (something like) https://book.validatingrdf.com in the future.

I'm therefore closing this issue now; hope you don't mind.
